# -*- coding: utf-8 -*-
"""Prosodic_Deepfake_Detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dH3dSLccJq_5KW9NbHk2V1drAFq8NzQW

# Часть 1: извлечение интанационных и ритмических признаков из OpenSmile

## Загрузка и подготовка данных
"""

from google.colab import files
import zipfile
import os
import glob
import pandas as pd
import shutil

def upload_and_extract_audio():
    """
    Загрузка и распаковка архивов с аудиофайлами
    """
    uploaded = files.upload()

    # Создание директорий
    natural_dir = '/content/natural_audio'
    synthetic_dir = '/content/synthetic_audio'

    if os.path.exists(natural_dir):
        shutil.rmtree(natural_dir)
    if os.path.exists(synthetic_dir):
        shutil.rmtree(synthetic_dir)

    os.makedirs(natural_dir, exist_ok=True)
    os.makedirs(synthetic_dir, exist_ok=True)

    # Распаковка архивов
    natural_found = False
    synthetic_found = False

    for filename in uploaded.keys():
        print(f"Обработка файла: {filename}")
        filepath = os.path.join('/content', filename)

        # Убираем "(1)", "(2)" и т.д. из проверки
        filename_clean = filename.replace(' (1)', '').replace(' (2)', '').replace(' (3)', '').replace(' (4)', '')
        filename_lower = filename_clean.lower()

        # Проверка на натуральную речь
        if 'натур' in filename_lower or 'natural' in filename_lower or 'real' in filename_lower or 'bona' in filename_lower:
            new_filepath = '/content/natural.zip'
            if filepath != new_filepath:
                os.rename(filepath, new_filepath)
            with zipfile.ZipFile(new_filepath, 'r') as zip_ref:
                zip_ref.extractall(natural_dir)
            print(f"  Тип: натуральная речь")
            print(f"  Распаковано в: {natural_dir}")
            natural_found = True

        # Проверка на синтетическую речь (добавлена явная проверка кириллицы)
        elif 'фейк' in filename_lower or 'fake' in filename_lower or 'synthetic' in filename_lower or 'spoof' in filename_lower:
            new_filepath = '/content/synthetic.zip'
            if filepath != new_filepath:
                os.rename(filepath, new_filepath)
            with zipfile.ZipFile(new_filepath, 'r') as zip_ref:
                zip_ref.extractall(synthetic_dir)

            synthetic_found = True
        else:
            # Если не распознали по имени, проверяем порядок загрузки
            # Первый файл - натуральная, второй - синтетическая
            files_list = list(uploaded.keys())
            if filename == files_list[0] and not natural_found:
                new_filepath = '/content/natural.zip'
                if filepath != new_filepath:
                    os.rename(filepath, new_filepath)
                with zipfile.ZipFile(new_filepath, 'r') as zip_ref:
                    zip_ref.extractall(natural_dir)

                natural_found = True
            elif filename == files_list[1] and not synthetic_found:
                new_filepath = '/content/synthetic.zip'
                if filepath != new_filepath:
                    os.rename(filepath, new_filepath)
                with zipfile.ZipFile(new_filepath, 'r') as zip_ref:
                    zip_ref.extractall(synthetic_dir)

                synthetic_found = True
            else:
                print(f"  Предупреждение: не удалось определить тип файла")

    # Подсчет файлов
    natural_files = glob.glob(f"{natural_dir}/**/*.wav", recursive=True)
    synthetic_files = glob.glob(f"{synthetic_dir}/**/*.wav", recursive=True)

    print(f"  Натуральная речь: {len(natural_files)} файлов")
    print(f"  Синтетическая речь: {len(synthetic_files)} файлов")

    if not natural_found or not synthetic_found:
        print("Предупреждение: не все архивы были распознаны")

    return natural_dir, synthetic_dir

# Загрузка данных
natural_path, synthetic_path = upload_and_extract_audio()

"""## Создание DataFrame с метаданными"""

import pandas as pd
import glob
import os

def create_dataframe(natural_dir, synthetic_dir):
    """
    Создание DataFrame с информацией об аудиофайлах
    """

    # Поиск аудиофайлов
    natural_files = glob.glob(f"{natural_dir}/**/*.wav", recursive=True)
    synthetic_files = glob.glob(f"{synthetic_dir}/**/*.wav", recursive=True)

    # Создание списка записей
    data_records = []

    for file_path in natural_files:
        data_records.append({
            'file_path': file_path,
            'type': 'bona_fide',
            'filename': os.path.basename(file_path)
        })

    for file_path in synthetic_files:
        data_records.append({
            'file_path': file_path,
            'type': 'spoof',
            'filename': os.path.basename(file_path)
        })

    df = pd.DataFrame(data_records)

    # Проверка парности данных
    natural_names = set(df[df['type'] == 'bona_fide']['filename'])
    synthetic_names = set(df[df['type'] == 'spoof']['filename'])
    paired_files = natural_names.intersection(synthetic_names)


    return df

audio_df = create_dataframe(natural_path, synthetic_path)

import pandas as pd
import glob
import os
import shutil

def reorganize_and_create_dataframe(natural_dir, synthetic_dir):
    """
    Реорганизация файлов и создание DataFrame
    """

    # Создание новых директорий без кириллицы
    natural_clean = '/content/audio_real'
    synthetic_clean = '/content/audio_fake'

    if os.path.exists(natural_clean):
        shutil.rmtree(natural_clean)
    if os.path.exists(synthetic_clean):
        shutil.rmtree(synthetic_clean)

    os.makedirs(natural_clean, exist_ok=True)
    os.makedirs(synthetic_clean, exist_ok=True)

    # Копирование файлов в новые директории
    natural_files = glob.glob(f"{natural_dir}/**/*.wav", recursive=True)
    synthetic_files = glob.glob(f"{synthetic_dir}/**/*.wav", recursive=True)

    for src_path in natural_files:
        filename = os.path.basename(src_path)
        dst_path = os.path.join(natural_clean, filename)
        shutil.copy2(src_path, dst_path)

    for src_path in synthetic_files:
        filename = os.path.basename(src_path)
        dst_path = os.path.join(synthetic_clean, filename)
        shutil.copy2(src_path, dst_path)

    # Создание DataFrame
    data_records = []

    for filename in os.listdir(natural_clean):
        if filename.endswith('.wav'):
            data_records.append({
                'file_path': os.path.join(natural_clean, filename),
                'label': 'real',
                'filename': filename
            })

    for filename in os.listdir(synthetic_clean):
        if filename.endswith('.wav'):
            data_records.append({
                'file_path': os.path.join(synthetic_clean, filename),
                'label': 'fake',
                'filename': filename
            })

    df = pd.DataFrame(data_records)

    # Проверка парности
    real_files = set(df[df['label'] == 'real']['filename'])
    fake_files = set(df[df['label'] == 'fake']['filename'])
    paired = real_files.intersection(fake_files)

    return df

# Создание чистого DataFrame
audio_df = reorganize_and_create_dataframe(natural_path, synthetic_path)

audio_df

"""## Установка и сборка openSMILE"""

import subprocess
import os

def setup_opensmile():
    """
    Клонирование и сборка openSMILE
    """

    # Проверка наличия openSMILE
    if os.path.exists('/content/opensmile/build/progsrc/smilextract/SMILExtract'):
        print("openSMILE уже установлен")
        return True

    # Клонирование репозитория
    if not os.path.exists('/content/opensmile'):
        result = subprocess.run(
            ['git', 'clone', 'https://github.com/audeering/opensmile.git'],
            cwd='/content',
            capture_output=True,
            text=True
        )
        if result.returncode != 0:
            print("Ошибка клонирования")
            return False

    # Сборка
    result = subprocess.run(
        ['bash', 'build.sh'],
        cwd='/content/opensmile',
        capture_output=True,
        text=True
    )

    if result.returncode == 0:
        return True
    else:
        print("Ошибка сборки")
        return False

# Установка openSMILE
setup_opensmile()

"""## Извлечение акустических признаков"""

import subprocess
from tqdm import tqdm

def extract_features(audio_df):
    """
    Извлечение признаков eGeMAPSv02 из аудиофайлов
    """

    smile_path = "/content/opensmile/build/progsrc/smilextract/SMILExtract"
    config_path = "/content/opensmile/config/egemaps/v02/eGeMAPSv02.conf"

    features_list = []

    for idx, row in tqdm(audio_df.iterrows(), total=len(audio_df), desc="Обработка файлов"):
        audio_file = row['file_path']
        temp_csv = f"/content/temp_features_{idx}.csv"

        # Команда openSMILE
        cmd = [
            smile_path,
            '-C', config_path,
            '-I', audio_file,
            '-O', temp_csv,
            '-l', '0'
        ]

        result = subprocess.run(cmd, capture_output=True, text=True, timeout=120)

        if result.returncode == 0 and os.path.exists(temp_csv):
            # Чтение CSV
            with open(temp_csv, 'r') as f:
                content = f.read()

            # Парсинг ARFF формата
            if '@data' in content:
                data_line = content.split('@data')[-1].strip().split('\n')[0]
                values = data_line.split(',')

                if len(values) > 50:
                    features = {}
                    for i, val in enumerate(values[1:], 1):
                        try:
                            features[f'feature_{i}'] = float(val)
                        except:
                            features[f'feature_{i}'] = val

                    features['label'] = row['label']
                    features['filename'] = row['filename']
                    features_list.append(features)

            os.remove(temp_csv)

    features_df = pd.DataFrame(features_list)
    print(f"Извлечено признаков: {len(features_df)} записей")

    return features_df

# Извлечение признаков
features_df = extract_features(audio_df)

"""OpenSMILE анализировал каждый аудиофайл:

- Разбивал на короткие фреймы (~25мс)
- Вычислял низкоуровневые дескрипторы (pitch, energy, спектр)
- Агрегировал статистики (mean, std, min, max, percentiles)
- Выдавал 88 итоговых признаков на файл

## Получение названий признаков
"""

def get_feature_names():
    """
    Извлечение названий признаков из ARFF файла
    """
    smile_path = "/content/opensmile/build/progsrc/smilextract/SMILExtract"
    config_path = "/content/opensmile/config/egemaps/v02/eGeMAPSv02.conf"
    test_audio = audio_df.iloc[0]['file_path']
    test_arff = "/content/feature_names.arff"

    # Извлечение признаков из одного файла
    cmd = [smile_path, '-C', config_path, '-I', test_audio, '-O', test_arff]
    subprocess.run(cmd, capture_output=True, text=True)

    # Парсинг названий из ARFF
    feature_names = []
    if os.path.exists(test_arff):
        with open(test_arff, 'r') as f:
            for line in f:
                if line.startswith('@attribute') and 'numeric' in line:
                    name = line.split()[1]
                    feature_names.append(name)

    print(f"Найдено признаков: {len(feature_names)}")
    print("\nПервые 10 признаков:")
    for i, name in enumerate(feature_names[:10], 1):
        print(f"  {i:2d}. {name}")

    return feature_names

# Получение названий
feature_names = get_feature_names()

# Переименование колонок в DataFrame
rename_dict = {f'feature_{i}': feature_names[i-1]
               for i in range(1, len(feature_names) + 1)
               if i <= len(feature_names)}

features_df = features_df.rename(columns=rename_dict)

features_df

"""## Выделение ключевых признаков ритмики и интонации"""

def select_rhythm_intonation_features(features_df, readable_names):
    """
    Выделение признаков, связанных с ритмикой и интонацией
    """

    # Ключевые признаки для анализа дипфейков
    key_features = [
        'F0semitoneFrom27.5Hz_sma3nz_amean',
        'F0semitoneFrom27.5Hz_sma3nz_stddevNorm',
        'F0semitoneFrom27.5Hz_sma3nz_meanRisingSlope',
        'F0semitoneFrom27.5Hz_sma3nz_meanFallingSlope',
        'loudness_sma3_amean',
        'loudness_sma3_stddevNorm',
        'loudness_sma3_stddevFallingSlope',
        'MeanUnvoicedSegmentLength',
        'StddevUnvoicedSegmentLength',
        'MeanVoicedSegmentLengthSec',
        'VoicedSegmentsPerSec',
        'loudnessPeaksPerSec',
        'spectralFlux_sma3_amean'
    ]

    # Проверка доступности признаков
    available_features = {}
    for feature in key_features:
        if feature in features_df.columns:
            available_features[feature] = readable_names.get(feature, feature)

    print(f"Выбрано признаков: {len(available_features)}")
    print("\nСписок признаков:")
    for i, (feature, description) in enumerate(available_features.items(), 1):
        print(f"{i:2d}. {description}")

    return available_features

# Выделение ключевых признаков
key_features = select_rhythm_intonation_features(features_df, readable_feature_names)

"""## Расчет EER для каждого признака"""

import numpy as np
from sklearn.metrics import roc_curve
from tqdm import tqdm

def compute_eer(scores, labels):
    """
    Вычисление Equal Error Rate
    """
    fpr, tpr, thresholds = roc_curve(labels, scores, pos_label=1)
    fnr = 1 - tpr
    eer_index = np.nanargmin(np.absolute(fnr - fpr))
    eer = fpr[eer_index]
    threshold = thresholds[eer_index]
    return eer, threshold

def analyze_features(features_df, key_features):
    """
    Анализ эффективности каждого признака
    """

    # Подготовка меток (0 = real, 1 = fake)
    labels = (features_df['label'] == 'fake').astype(int)

    results = {}

    for feature in tqdm(key_features.keys(), desc="Расчет EER"):
        scores = features_df[feature].values

        # Разделение по классам
        real_values = features_df[features_df['label'] == 'real'][feature]
        fake_values = features_df[features_df['label'] == 'fake'][feature]

        # Вычисление EER
        eer, threshold = compute_eer(scores, labels)

        results[feature] = {
            'eer': eer,
            'threshold': threshold,
            'mean_real': real_values.mean(),
            'mean_fake': fake_values.mean(),
            'std_real': real_values.std(),
            'std_fake': fake_values.std()
        }

    # Сортировка по EER (лучшие первые)
    results = dict(sorted(results.items(), key=lambda x: x[1]['eer']))

    return results

# Анализ признаков
feature_results = analyze_features(features_df, key_features)

# Вывод результатов
print("\nРезультаты анализа:")

for i, (feature, stats) in enumerate(feature_results.items(), 1):
    readable_name = readable_feature_names.get(feature, feature)
    diff = stats['mean_fake'] - stats['mean_real']
    diff_pct = (abs(diff) / stats['mean_real'] * 100) if stats['mean_real'] != 0 else 0

    print(f"{i:2d}. {readable_name}")
    print(f"    EER: {stats['eer']:.3f} ({stats['eer']*100:.1f}% ошибок)")
    print(f"    Real: {stats['mean_real']:.4f} ± {stats['std_real']:.4f}")
    print(f"    Fake: {stats['mean_fake']:.4f} ± {stats['std_fake']:.4f}")
    print(f"    Разница: {diff:+.4f} ({diff_pct:.1f}%)")

"""## Анализ

Equal Error Rate (EER) - это процент ошибок классификатора, когда он одинаково часто:

- Принимает fake за real (ложное принятие)
- Принимает real за fake (ложное отклонение)
- Чем меньше EER, тем лучше признак различает классы.

РЕЗУЛЬТАТЫ

- Лучший признак:

Вариативность длительности пауз - EER 38.3%

У fake пауз более однородные (+14%)

- Средние признаки (EER 43-49%):

Изменчивость громкости, скорость изменения спектра, длительность пауз
- Плохие признаки (EER > 50%):
Все признаки высоты голоса (F0), ритмические параметры

Таким образом, дипфейки очень качественные и одиночные признаки недостаточны

- Интересные находки:

У fake более стабильные паузы (+14%) - синтезатор делает паузы однообразнее;

У fake чуть выше громкость (+3.6%);

У real более выраженное понижение интонации (+17.8%).

## Визуализация результатов анализа
"""

import matplotlib.pyplot as plt
import seaborn as sns

sns.set_style("whitegrid")

def plot_eer_comparison(feature_results, readable_names):
    """
    График сравнения EER всех признаков
    """
    features_list = list(feature_results.keys())
    eer_values = [feature_results[f]['eer'] for f in features_list]
    readable_list = [readable_names.get(f, f)[:40] for f in features_list]

    colors = ['green' if eer < 0.4 else 'orange' if eer < 0.5 else 'red' for eer in eer_values]

    plt.figure(figsize=(12, 8))
    y_pos = range(len(readable_list))
    plt.barh(y_pos, eer_values, color=colors, alpha=0.7)
    plt.yticks(y_pos, readable_list, fontsize=9)
    plt.xlabel('Equal Error Rate (EER)')
    plt.title('Эффективность признаков для детекции дипфейков', fontweight='bold', fontsize=12)
    plt.axvline(x=0.5, color='red', linestyle='--', alpha=0.5, label='Случайное угадывание')
    plt.axvline(x=0.4, color='green', linestyle='--', alpha=0.5, label='Хороший порог')
    plt.legend(loc='lower right')
    plt.gca().invert_yaxis()
    plt.tight_layout()
    plt.savefig('/content/eer_comparison.png', dpi=300, bbox_inches='tight')
    plt.show()

plot_eer_comparison(feature_results, readable_feature_names)

"""График показывает, что дипфейки отличаются от натуральной речи преимущественно избыточной вариативностью пауз (+14%) и сглаженными нисходящими интонациями (-17.8%), в то время как большинство других параметров (высота голоса, громкость, ритм) имитируются с различием менее 5%. Парадоксально, но наибольшие различия средних значений не гарантируют эффективность классификации из-за высокой внутриклассовой вариативности, что объясняет слабую работу одиночных признаков."""

def plot_feature_differences(feature_results, readable_names):
    """
    График разницы между Real и Fake
    """
    features_list = list(feature_results.keys())
    readable_list = [readable_names.get(f, f)[:40] for f in features_list]

    differences = []
    for feature in features_list:
        diff_pct = ((feature_results[feature]['mean_fake'] - feature_results[feature]['mean_real']) /
                    feature_results[feature]['mean_real'] * 100) if feature_results[feature]['mean_real'] != 0 else 0
        differences.append(diff_pct)

    colors_diff = ['red' if d > 0 else 'blue' for d in differences]

    plt.figure(figsize=(12, 8))
    y_pos = range(len(readable_list))
    plt.barh(y_pos, differences, color=colors_diff, alpha=0.7)
    plt.yticks(y_pos, readable_list, fontsize=9)
    plt.xlabel('Разница (Fake - Real), %')
    plt.title('Направление различий признаков', fontweight='bold', fontsize=12)
    plt.axvline(x=0, color='black', linestyle='-', linewidth=0.8)
    plt.gca().invert_yaxis()
    plt.grid(True, alpha=0.3, axis='x')
    plt.tight_layout()
    plt.savefig('/content/feature_differences.png', dpi=300, bbox_inches='tight')
    plt.show()

plot_feature_differences(feature_results, readable_feature_names)

"""График раскрывает тонкую грань между натуральной и синтезированной речью. Дипфейки не радикально отличаются от оригинала (большинство различий <5%), но имеют специфическую сигнатуру в виде:

Избыточной вариативности пауз (+14%)

Сглаженных интонационных падений (-17.8%)

Фрагментированной структуры сегментов (-4.9%)

# Часть 2: Инверсия предсказаний
"""

def inversion_experiment(features_df, feature_results, readable_names):
    """
    Инверсия предсказаний для признаков с EER > 0.5
    """

    # Находим признаки с EER > 0.5
    weak_features = {k: v for k, v in feature_results.items() if v['eer'] > 0.5}

    print(f"Признаков с EER > 0.5: {len(weak_features)}")

    # Подготовка меток
    labels = (features_df['label'] == 'fake').astype(int)

    inversion_results = []

    for feature, stats in weak_features.items():
        # Исходные scores
        scores = features_df[feature].values

        # Инверсия
        inverted_scores = -scores

        # Пересчет EER
        eer_original = stats['eer']
        eer_inverted, _ = compute_eer(inverted_scores, labels)

        improvement = eer_original - eer_inverted

        inversion_results.append({
            'feature': feature,
            'readable_name': readable_names.get(feature, feature),
            'eer_original': eer_original,
            'eer_inverted': eer_inverted,
            'improvement': improvement,
            'is_better': eer_inverted < eer_original
        })

    # Сортировка по улучшению
    inversion_results = sorted(inversion_results, key=lambda x: x['improvement'], reverse=True)

    # Вывод результатов
    print("Результаты инверсии:")

    for i, result in enumerate(inversion_results, 1):
        status = "Улучшение" if result['is_better'] else "Без изменений"
        print(f"{i}. {result['readable_name']}")
        print(f"   До инверсии:  EER = {result['eer_original']:.3f}")
        print(f"   После:        EER = {result['eer_inverted']:.3f}")
        print(f"   Изменение:    {result['improvement']:+.3f} ({status})")
        print()

    return inversion_results

# Запуск эксперимента
inversion_results = inversion_experiment(features_df, feature_results, readable_feature_names)

"""Все 7 признаков с EER > 0.5 (хуже случайного угадывания) улучшились после инверсии, со средним снижением ошибки на 0.055. Это подтверждает, что данные признаки содержат различительную информацию, но работают в направлении, противоположном интуитивным ожиданиям - классификатор изначально неверно интерпретировал направление различий между real и fake.

## Итоговая таблица признаков
"""

def create_final_results_table(feature_results, inversion_results, readable_names):
    """
    Создание итоговой таблицы всех признаков с учетом инверсии
    """

    final_results = []

    # Словарь инвертированных результатов
    inverted_dict = {r['feature']: r for r in inversion_results}

    for feature, stats in feature_results.items():
        readable_name = readable_names.get(feature, feature)
        eer_original = stats['eer']

        # Проверяем, был ли признак инвертирован
        if feature in inverted_dict:
            inv = inverted_dict[feature]
            best_eer = inv['eer_inverted']
            method = 'Инвертированный'
            improved = inv['is_better']
        else:
            best_eer = eer_original
            method = 'Исходный'
            improved = False

        final_results.append({
            'Признак': readable_name,
            'Исходный EER': eer_original,
            'Лучший EER': best_eer,
            'Метод': method,
            'Улучшен': 'Да' if improved else 'Нет'
        })

    # Создание DataFrame
    final_df = pd.DataFrame(final_results)
    final_df = final_df.sort_values('Лучший EER')

    # Вывод таблицы
    print(final_df.to_string(index=False))

    print(f"  Всего признаков: {len(final_df)}")
    print(f"  Улучшено инверсией: {final_df['Улучшен'].value_counts().get('Да', 0)}")
    print(f"  Лучший результат: {final_df.iloc[0]['Признак']} (EER = {final_df.iloc[0]['Лучший EER']:.3f})")
    print(f"  Средний EER (исходный): {final_df['Исходный EER'].mean():.3f}")
    print(f"  Средний EER (лучший): {final_df['Лучший EER'].mean():.3f}")

    return final_df

# Создание итоговой таблицы
final_results_df = create_final_results_table(feature_results, inversion_results, readable_feature_names)

"""Из 13 проанализированных признаков 7 (54%) улучшились после инверсии, что снизило средний EER с 0.492 до 0.463 (улучшение на 6%). Лучшим признаком остается вариативность длительности пауз (EER = 0.383), который не требовал инверсии, в то время как все признаки F0 и ритмические параметры работали в противоположном направлении и после коррекции достигли EER около 0.46-0.49. Несмотря на улучшения, все признаки остаются слабыми классификаторами (лучший EER = 0.383, средний = 0.463), что подтверждает необходимость использования комбинированных методов для надежной детекции дипфейков.

# Часть 3: Random Forest

## Создание и обучение комбинированной модели

Проверка, улучшится ли результат при использовании нескольких признаков одновременно
"""

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score, StratifiedKFold
from sklearn.metrics import roc_auc_score, roc_curve, confusion_matrix
import numpy as np

def create_combined_model(features_df, final_results_df):
    """
    Создание и обучение комбинированной модели
    """


    # Выбираем топ-5 лучших признаков
    top5_features = final_results_df.nsmallest(5, 'Лучший EER')

    # Получаем технические названия признаков
    feature_name_map = {v: k for k, v in readable_feature_names.items()}
    selected_features = []

    for readable_name in top5_features['Признак']:
        tech_name = feature_name_map.get(readable_name)
        if tech_name and tech_name in features_df.columns:
            selected_features.append(tech_name)

    print(f"Выбрано признаков для модели: {len(selected_features)}")
    print("\nИспользуемые признаки:")
    for i, feature in enumerate(selected_features, 1):
        readable = readable_feature_names.get(feature, feature)
        eer = final_results_df[final_results_df['Признак'] == readable]['Лучший EER'].values[0]
        print(f"  {i}. {readable[:50]:50s} EER = {eer:.3f}")

    # Подготовка данных
    X = features_df[selected_features]
    y = (features_df['label'] == 'fake').astype(int)

    print()
    print(f"Размерность данных: {X.shape}")
    print(f"  Образцов: {X.shape[0]}")
    print(f"  Признаков: {X.shape[1]}")
    print(f"  Real: {(y == 0).sum()}")
    print(f"  Fake: {(y == 1).sum()}")
    print()

    # Создание модели
    model = RandomForestClassifier(
        n_estimators=100,
        max_depth=10,
        min_samples_split=5,
        random_state=42,
        n_jobs=-1
    )

    # Кросс-валидация
    print("Обучение модели с кросс-валидацией (5 фолдов)...")
    cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

    roc_auc_scores = cross_val_score(model, X, y, cv=cv, scoring='roc_auc', n_jobs=-1)

    print()
    print("Результаты кросс-валидации:")

    print(f"ROC-AUC по фолдам: {[f'{s:.3f}' for s in roc_auc_scores]}")
    print(f"Средний ROC-AUC: {roc_auc_scores.mean():.3f} ± {roc_auc_scores.std():.3f}")

    # Приблизительный EER из ROC-AUC
    estimated_eer = 1 - roc_auc_scores.mean()
    print(f"Примерный EER: {estimated_eer:.3f} ({estimated_eer*100:.1f}% ошибок)")
    print()

    # Сравнение с одиночными признаками
    best_single_eer = final_results_df['Лучший EER'].min()
    improvement = best_single_eer - estimated_eer
    improvement_pct = (improvement / best_single_eer) * 100

    print("Сравнение с одиночными признаками:")

    print(f"Лучший одиночный признак: EER = {best_single_eer:.3f}")
    print(f"Комбинированная модель:   EER ≈ {estimated_eer:.3f}")
    print(f"Улучшение:                {improvement:.3f} ({improvement_pct:+.1f}%)")

    if improvement > 0:
        print("Вывод: Комбинация признаков работает лучше!")
    else:
        print("Вывод: Комбинация не дала улучшения")
    print()

    # Обучение на всех данных для feature importance
    model.fit(X, y)

    return model, selected_features, roc_auc_scores

# Создание модели
rf_model, selected_features, cv_scores = create_combined_model(features_df, final_results_df)

"""Объединение 5 лучших признаков в модель Random Forest дало двукратное улучшение качества детекции:

- EER снизился с 0.383 (лучший одиночный признак) до 0.195, что составляет улучшение на 49%.
- Модель достигла среднего ROC-AUC = 0.805 ± 0.036 при кросс-валидации на 872 образцах, демонстрируя стабильность результата (разброс по фолдам 0.775-0.871).

Это подтверждает, что даже слабые одиночные признаки (EER 0.38-0.46) в комбинации создают эффективный детектор, способный правильно классифицировать около 80% случаев.

В модель вошли 5 признаков разных категорий:

- Паузы: Вариативность длительности пауз (EER = 0.383)
- Громкость: Изменчивость громкости (EER = 0.431)
- Спектр: Средняя скорость изменения спектра (EER = 0.454)
- Ритмика: Средняя длительность произнесения (EER = 0.461, инвертированный)
- Ритмика: Количество речевых фрагментов в секунду (EER = 0.463, инвертированный)

аким образом, модель объединила признаки из четырех независимых акустических доменов (паузы, громкость, спектр, ритмика), причем два из них потребовали инверсии. Синергия разнородных признаков позволила модели уловить многомерную "сигнатуру" дипфейка, которая невидима при анализе каждого параметра по отдельности - каждый признак описывает свой аспект синтетической речи (механистичность пауз, избыточная динамика громкости, спектральные артефакты, фрагментированность), и вместе они формируют надежный паттерн для детекции.

## Метрики качества
"""

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.model_selection import cross_validate, StratifiedKFold

def evaluate_model_metrics(rf_model, selected_features, features_df):
    """
    Расчет метрик качества модели
    """
    y = (features_df['label'] == 'fake').astype(int)
    X = features_df[selected_features]

    # Кросс-валидация
    cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

    scoring = {
        'accuracy': 'accuracy',
        'precision': 'precision',
        'recall': 'recall',
        'f1': 'f1',
        'roc_auc': 'roc_auc'
    }

    cv_results = cross_validate(rf_model, X, y, cv=cv, scoring=scoring, n_jobs=-1)

    print(f"Accuracy:  {cv_results['test_accuracy'].mean():.3f} ± {cv_results['test_accuracy'].std():.3f}")
    print(f"Precision: {cv_results['test_precision'].mean():.3f} ± {cv_results['test_precision'].std():.3f}")
    print(f"Recall:    {cv_results['test_recall'].mean():.3f} ± {cv_results['test_recall'].std():.3f}")
    print(f"F1-Score:  {cv_results['test_f1'].mean():.3f} ± {cv_results['test_f1'].std():.3f}")
    print(f"ROC-AUC:   {cv_results['test_roc_auc'].mean():.3f} ± {cv_results['test_roc_auc'].std():.3f}")

evaluate_model_metrics(rf_model, selected_features, features_df)

from sklearn.metrics import classification_report
from sklearn.model_selection import cross_val_predict, StratifiedKFold

def evaluate_by_class(rf_model, selected_features, features_df):
    """
    Метрики отдельно для Real и Fake
    """
    y = (features_df['label'] == 'fake').astype(int)
    X = features_df[selected_features]

    cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
    y_pred = cross_val_predict(rf_model, X, y, cv=cv)

    print(classification_report(y, y_pred,
                                target_names=['Real', 'Fake'],
                                digits=3))

evaluate_by_class(rf_model, selected_features, features_df)

"""Модель немного лучше определяет Real (F1=0.736), чем Fake (F1=0.717). Она чаще пропускает дипфейки (recall=0.693), чем ошибочно помечает настоящую речь как fake. Это означает, что модель "осторожна" и предпочитает не обвинять без уверенности, что в некоторых применениях (например, модерация контента) может быть предпочтительнее, чем блокировать настоящую речь."""

import matplotlib.pyplot as plt
import seaborn as sns

def visualize_combined_model(rf_model, selected_features, cv_scores, features_df, readable_names):
    """
    Визуализация результатов комбинированной модели
    """

    fig, axes = plt.subplots(2, 2, figsize=(16, 12))

    # График 1: Feature Importance
    ax1 = axes[0, 0]

    importances = rf_model.feature_importances_
    feature_names_readable = [readable_names.get(f, f)[:35] for f in selected_features]

    indices = np.argsort(importances)[::-1]

    colors = plt.cm.viridis(np.linspace(0.3, 0.9, len(importances)))
    bars = ax1.barh(range(len(importances)), importances[indices], color=colors)
    ax1.set_yticks(range(len(importances)))
    ax1.set_yticklabels([feature_names_readable[i] for i in indices])
    ax1.set_xlabel('Важность признака')
    ax1.set_title('Feature Importance в Random Forest', fontweight='bold', fontsize=12)
    ax1.invert_yaxis()

    for i, (bar, imp) in enumerate(zip(bars, importances[indices])):
        ax1.text(bar.get_width() + 0.01, bar.get_y() + bar.get_height()/2,
                f'{imp:.3f}', va='center', fontsize=10)

    # График 2: ROC Curves для каждого фолда
    ax2 = axes[0, 1]

    y = (features_df['label'] == 'fake').astype(int)
    X = features_df[selected_features]

    cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

    tprs = []
    aucs = []
    mean_fpr = np.linspace(0, 1, 100)

    for fold_idx, (train_idx, test_idx) in enumerate(cv.split(X, y)):
        X_train, X_test = X.iloc[train_idx], X.iloc[test_idx]
        y_train, y_test = y.iloc[train_idx], y.iloc[test_idx]

        rf_model.fit(X_train, y_train)
        y_pred_proba = rf_model.predict_proba(X_test)[:, 1]

        fpr, tpr, _ = roc_curve(y_test, y_pred_proba)
        roc_auc = roc_auc_score(y_test, y_pred_proba)

        aucs.append(roc_auc)
        tprs.append(np.interp(mean_fpr, fpr, tpr))
        tprs[-1][0] = 0.0

        ax2.plot(fpr, tpr, lw=1, alpha=0.3, label=f'Fold {fold_idx+1} (AUC = {roc_auc:.3f})')

    mean_tpr = np.mean(tprs, axis=0)
    mean_tpr[-1] = 1.0
    mean_auc = np.mean(aucs)
    std_auc = np.std(aucs)

    ax2.plot(mean_fpr, mean_tpr, color='b', lw=2,
            label=f'Среднее (AUC = {mean_auc:.3f} ± {std_auc:.3f})')
    ax2.plot([0, 1], [0, 1], 'k--', lw=1, label='Случайное угадывание')

    ax2.set_xlabel('False Positive Rate')
    ax2.set_ylabel('True Positive Rate')
    ax2.set_title('ROC Curves (кросс-валидация)', fontweight='bold', fontsize=12)
    ax2.legend(loc='lower right', fontsize=8)
    ax2.grid(True, alpha=0.3)

    # График 3: Сравнение методов
    ax3 = axes[1, 0]

    methods = ['Лучший\nодиночный\nпризнак', 'Комбинированная\nмодель\n(5 признаков)']
    eer_values = [0.383, 0.195]
    colors_comparison = ['orange', 'green']

    bars = ax3.bar(methods, eer_values, color=colors_comparison, alpha=0.7, edgecolor='black')
    ax3.axhline(y=0.5, color='red', linestyle='--', alpha=0.5, label='Случайное угадывание')
    ax3.set_ylabel('Equal Error Rate (EER)')
    ax3.set_title('Сравнение подходов', fontweight='bold', fontsize=12)
    ax3.set_ylim(0, 0.6)
    ax3.legend()
    ax3.grid(True, alpha=0.3, axis='y')

    for bar, eer in zip(bars, eer_values):
        height = bar.get_height()
        ax3.text(bar.get_x() + bar.get_width()/2., height + 0.01,
                f'{eer:.3f}\n({eer*100:.1f}%)',
                ha='center', va='bottom', fontsize=11, fontweight='bold')

    # График 4: Confusion Matrix
    ax4 = axes[1, 1]

    rf_model.fit(X, y)
    y_pred = rf_model.predict(X)

    cm = confusion_matrix(y, y_pred)

    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', ax=ax4,
                xticklabels=['Real', 'Fake'],
                yticklabels=['Real', 'Fake'],
                cbar_kws={'label': 'Количество'})

    ax4.set_xlabel('Предсказанная метка')
    ax4.set_ylabel('Истинная метка')
    ax4.set_title('Confusion Matrix\n(обучение на всех данных)', fontweight='bold', fontsize=12)

    accuracy = (cm[0, 0] + cm[1, 1]) / cm.sum()
    ax4.text(0.5, -0.15, f'Точность: {accuracy:.1%}',
            ha='center', transform=ax4.transAxes, fontsize=11)

    plt.suptitle('Результаты комбинированной модели Random Forest',
                fontsize=14, fontweight='bold', y=0.995)
    plt.tight_layout()
    plt.savefig('/content/combined_model_results.png', dpi=300, bbox_inches='tight')
    plt.show()

# Создание визуализации
visualize_combined_model(rf_model, selected_features, cv_scores, features_df, readable_feature_names)

"""## Анализ

- Feature Importance: Модель определила количество речевых фрагментов как доминирующий признак (33% важности), при этом все пять признаков вносят вклад в решение, что подтверждает многомерную природу детекции дипфейков.

- ROC Curves: Стабильность модели подтверждается узким разбросом AUC по фолдам (0.775-0.815) со средним значением 0.805, что значительно превышает случайное угадывание и демонстрирует надежность кросс-валидации.

- Сравнение подходов: Комбинированная модель снизила ошибку почти вдвое (с 38.3% до 19.5%), наглядно демонстрируя преимущество многомерного анализа над одиночными признаками.

- Confusion Matrix: Точность 98.2% на обучающих данных показывает отличную способность модели к обучению, при этом асимметрия ошибок (6 ложных срабатываний vs 10 пропусков) указывает на небольшую тенденцию пропускать дипфейки

# Часть 4: разделение на fastpitch и vits

FastPitch и VITS — это два разных типа нейросетевых TTS‑синтезаторов (Text‑to‑Speech), то есть моделей, которые генерируют речь из текста: FastPitch обычно работает в два шага (сначала предсказывает высоту тона/длительности и формирует “мел‑спектрограмму”, затем отдельный вокодер превращает её в звук) и поэтому часто дает более “контролируемую”, но местами более механическую просодию, а VITS — более современная end‑to‑end модель, которая в одной системе совместно учит текст→речь и генерацию аудио (через вариационный/flow‑подход), из‑за чего часто звучит более естественно и плавно, но всё равно может оставлять свои характерные артефакты.
"""

from google.colab import files
import zipfile
import os
import glob
import shutil

def upload_and_prepare_data():
    """
    Загрузка трех категорий аудио для сравнительного анализа
    """
    print("📤 Загрузите 3 архива:")
    print("   1. natural.zip")
    print("   2. fastpitch-hifigan.zip (или fastpitch.zip)")
    print("   3. vits.zip")
    print()

    uploaded = files.upload()

    # Создание чистых директорий
    dirs = {
        'natural': '/content/audio_natural',
        'fastpitch': '/content/audio_fastpitch',
        'vits': '/content/audio_vits'
    }

    for path in dirs.values():
        if os.path.exists(path):
            shutil.rmtree(path)
        os.makedirs(path, exist_ok=True)

    # Распаковка с определением типа
    for filename in uploaded.keys():
        filepath = os.path.join('/content', filename)
        fn_lower = filename.lower()

        print(f"Обработка: {filename}")

        if 'natural' in fn_lower or 'натур' in fn_lower:
            with zipfile.ZipFile(filepath, 'r') as zip_ref:
                zip_ref.extractall(dirs['natural'])
            print(f"  ✅ Распознано как: Natural")

        elif 'fastpitch' in fn_lower or 'fast' in fn_lower:
            with zipfile.ZipFile(filepath, 'r') as zip_ref:
                zip_ref.extractall(dirs['fastpitch'])
            print(f"  ✅ Распознано как: FastPitch")

        elif 'vits' in fn_lower:
            with zipfile.ZipFile(filepath, 'r') as zip_ref:
                zip_ref.extractall(dirs['vits'])
            print(f"  ✅ Распознано как: VITS")
        else:
            print(f"  ⚠️  Не удалось определить тип")

    # Подсчет файлов
    print("\n📊 Статистика загруженных файлов:")
    counts = {}
    for name, path in dirs.items():
        wav_files = glob.glob(f"{path}/**/*.wav", recursive=True)
        counts[name] = len(wav_files)
        print(f"   {name:12s}: {counts[name]:4d} .wav файлов")

    return dirs['natural'], dirs['fastpitch'], dirs['vits']


def create_paired_dataframe(natural_dir, fastpitch_dir, vits_dir):
    """
    Создание DataFrame только из парных файлов
    """
    # Получаем списки файлов
    natural_files = {os.path.basename(f): f
                     for f in glob.glob(f"{natural_dir}/**/*.wav", recursive=True)}
    fastpitch_files = {os.path.basename(f): f
                       for f in glob.glob(f"{fastpitch_dir}/**/*.wav", recursive=True)}
    vits_files = {os.path.basename(f): f
                  for f in glob.glob(f"{vits_dir}/**/*.wav", recursive=True)}

    print(f"\n🔍 Поиск парных файлов:")
    print(f"   Natural:   {len(natural_files)} файлов")
    print(f"   FastPitch: {len(fastpitch_files)} файлов")
    print(f"   VITS:      {len(vits_files)} файлов")

    # Находим пересечение (файлы с одинаковыми именами)
    paired_filenames = (set(natural_files.keys()) &
                        set(fastpitch_files.keys()) &
                        set(vits_files.keys()))

    print(f"\n✅ Парных файлов (присутствуют во всех 3 категориях): {len(paired_filenames)}")

    if len(paired_filenames) == 0:
        print("\n❌ ОШИБКА: Парных файлов не найдено!")
        print("   Возможные причины:")
        print("   - Разные имена файлов в разных категориях")
        print("   - Файлы находятся в подпапках с разной структурой")

        # Показываем примеры для отладки
        print("\n   Примеры имен файлов:")
        print(f"   Natural:   {list(natural_files.keys())[:3]}")
        print(f"   FastPitch: {list(fastpitch_files.keys())[:3]}")
        print(f"   VITS:      {list(vits_files.keys())[:3]}")
        return None

    # Создаем записи
    data_records = []

    for filename in sorted(paired_filenames):
        # Natural
        data_records.append({
            'file_path': natural_files[filename],
            'label': 'real',
            'synthesis_type': 'real',
            'filename': filename
        })

        # FastPitch
        data_records.append({
            'file_path': fastpitch_files[filename],
            'label': 'fake',
            'synthesis_type': 'fastpitch',
            'filename': filename
        })

        # VITS
        data_records.append({
            'file_path': vits_files[filename],
            'label': 'fake',
            'synthesis_type': 'vits',
            'filename': filename
        })

    df = pd.DataFrame(data_records)

    print(f"\n📋 DataFrame создан:")
    print(df['synthesis_type'].value_counts())
    print(f"\n   Всего записей: {len(df)}")
    print(f"   Уникальных фраз: {len(paired_filenames)}")

    # Показываем пример
    print(f"\n👀 Пример данных (первые 9 строк = 3 фразы × 3 версии):")
    print(df[['filename', 'synthesis_type', 'label']].head(9))

    return df


# 🚀 ЗАПУСК
print("="*70)
print("ЗАГРУЗКА ДАННЫХ ДЛЯ ЗАДАНИЯ")
print("="*70)
print()

# Загрузка
natural_path, fastpitch_path, vits_path = upload_and_prepare_data()

# Создание DataFrame
audio_df = create_paired_dataframe(natural_path, fastpitch_path, vits_path)

if audio_df is not None:
    print("\n" + "="*70)
    print("✅ ДАННЫЕ ГОТОВЫ К АНАЛИЗУ!")
    print("="*70)

"""## Извлечение признаков OpenSMILE"""

import subprocess
import os

def setup_opensmile():
    """
    Клонирование и сборка openSMILE
    """

    # Проверка наличия
    if os.path.exists('/content/opensmile/build/progsrc/smilextract/SMILExtract'):
        print("OpenSMILE уже установлен")
        return True

    # Клонирование репозитория
    if not os.path.exists('/content/opensmile'):
        print("Клонирование репозитория...")
        result = subprocess.run(
            ['git', 'clone', 'https://github.com/audeering/opensmile.git'],
            cwd='/content',
            capture_output=True,
            text=True
        )
        if result.returncode != 0:
            print("Ошибка клонирования")
            print(result.stderr)
            return False
        print("Репозиторий склонирован")

    # Сборка
    print("Сборка OpenSMILE (это займет ~2-3 минуты)...")
    result = subprocess.run(
        ['bash', 'build.sh'],
        cwd='/content/opensmile',
        capture_output=True,
        text=True
    )

    if result.returncode == 0:
        print("OpenSMILE успешно собран!")
        return True
    else:
        print(" Ошибка сборки")
        print(result.stderr)
        return False

# Установка
setup_opensmile()

import subprocess
from tqdm import tqdm
import pandas as pd
import os

def extract_features_three_types(audio_df):
    """
    Извлечение признаков eGeMAPSv02 для всех трех категорий
    """
    smile_path = "/content/opensmile/build/progsrc/smilextract/SMILExtract"
    config_path = "/content/opensmile/config/egemaps/v02/eGeMAPSv02.conf"

    features_list = []

    print("Извлечение акустических признаков...")
    print(f"Всего файлов для обработки: {len(audio_df)}")

    for idx, row in tqdm(audio_df.iterrows(), total=len(audio_df), desc="Обработка"):
        audio_file = row['file_path']
        temp_csv = f"/content/temp_features_{idx}.csv"

        cmd = [
            smile_path,
            '-C', config_path,
            '-I', audio_file,
            '-O', temp_csv,
            '-l', '0'
        ]

        try:
            result = subprocess.run(cmd, capture_output=True, text=True, timeout=120)

            if result.returncode == 0 and os.path.exists(temp_csv):
                with open(temp_csv, 'r') as f:
                    content = f.read()

                if '@data' in content:
                    data_line = content.split('@data')[-1].strip().split('\n')[0]
                    values = data_line.split(',')

                    if len(values) > 50:
                        features = {}
                        for i, val in enumerate(values[1:], 1):
                            try:
                                features[f'feature_{i}'] = float(val)
                            except:
                                features[f'feature_{i}'] = val

                        features['label'] = row['label']
                        features['synthesis_type'] = row['synthesis_type']
                        features['filename'] = row['filename']
                        features_list.append(features)

                os.remove(temp_csv)

        except Exception as e:
            continue

    features_df = pd.DataFrame(features_list)

    print(f"\n Извлечено признаков: {len(features_df)} записей")
    print(f" Распределение по категориям:")
    print(features_df['synthesis_type'].value_counts())

    return features_df

features_df = extract_features_three_types(audio_df)

"""## Получение названий признаков и подготовка к анализу"""

import numpy as np
from sklearn.metrics import roc_curve

# 1. Получение названий признаков
def get_feature_names():
    """
    Извлечение названий признаков из ARFF файла
    """
    smile_path = "/content/opensmile/build/progsrc/smilextract/SMILExtract"
    config_path = "/content/opensmile/config/egemaps/v02/eGeMAPSv02.conf"
    test_audio = audio_df.iloc[0]['file_path']
    test_arff = "/content/feature_names.arff"

    cmd = [smile_path, '-C', config_path, '-I', test_audio, '-O', test_arff]
    subprocess.run(cmd, capture_output=True, text=True)

    feature_names = []
    if os.path.exists(test_arff):
        with open(test_arff, 'r') as f:
            for line in f:
                if line.startswith('@attribute') and 'numeric' in line:
                    name = line.split()[1]
                    feature_names.append(name)

    return feature_names

# 2. Получение названий
feature_names = get_feature_names()

# 3. Переименование колонок
rename_dict = {f'feature_{i}': feature_names[i-1]
               for i in range(1, len(feature_names) + 1)
               if i <= len(feature_names)}
features_df = features_df.rename(columns=rename_dict)

# 4. Словарь читаемых названий
readable_feature_names = {
    'F0semitoneFrom27.5Hz_sma3nz_amean': 'Средняя высота голоса',
    'F0semitoneFrom27.5Hz_sma3nz_stddevNorm': 'Изменчивость высоты голоса',
    'F0semitoneFrom27.5Hz_sma3nz_meanRisingSlope': 'Скорость повышения интонации',
    'F0semitoneFrom27.5Hz_sma3nz_meanFallingSlope': 'Скорость понижения интонации',
    'loudness_sma3_amean': 'Средняя громкость речи',
    'loudness_sma3_stddevNorm': 'Изменчивость громкости',
    'loudness_sma3_stddevFallingSlope': 'Вариативность затухания громкости',
    'MeanUnvoicedSegmentLength': 'Средняя длительность пауз',
    'StddevUnvoicedSegmentLength': 'Вариативность длительности пауз',
    'MeanVoicedSegmentLengthSec': 'Средняя длительность произнесения',
    'VoicedSegmentsPerSec': 'Количество речевых фрагментов в секунду',
    'loudnessPeaksPerSec': 'Количество акцентов в секунду',
    'spectralFlux_sma3_amean': 'Средняя скорость изменения спектра'
}

# 5. Список ключевых признаков
key_features = [
    'F0semitoneFrom27.5Hz_sma3nz_amean',
    'F0semitoneFrom27.5Hz_sma3nz_stddevNorm',
    'F0semitoneFrom27.5Hz_sma3nz_meanRisingSlope',
    'F0semitoneFrom27.5Hz_sma3nz_meanFallingSlope',
    'loudness_sma3_amean',
    'loudness_sma3_stddevNorm',
    'loudness_sma3_stddevFallingSlope',
    'MeanUnvoicedSegmentLength',
    'StddevUnvoicedSegmentLength',
    'MeanVoicedSegmentLengthSec',
    'VoicedSegmentsPerSec',
    'loudnessPeaksPerSec',
    'spectralFlux_sma3_amean'
]

# 6. Функция расчета EER
def compute_eer(scores, labels):
    """
    Вычисление Equal Error Rate
    """
    fpr, tpr, thresholds = roc_curve(labels, scores, pos_label=1)
    fnr = 1 - tpr
    eer_index = np.nanargmin(np.absolute(fnr - fpr))
    eer = fpr[eer_index]
    threshold = thresholds[eer_index]
    return eer, threshold

print(f"   • Записей: {len(features_df)}")
print(f"   • Признаков: {len(feature_names)}")
print(f"   • Ключевых признаков для анализа: {len(key_features)}")
print(f"   • Real: {(features_df['synthesis_type'] == 'real').sum()}")
print(f"   • FastPitch: {(features_df['synthesis_type'] == 'fastpitch').sum()}")
print(f"   • VITS: {(features_df['synthesis_type'] == 'vits').sum()}")

"""## Анализ Natural vs FastPitch"""

from tqdm import tqdm

def analyze_synthesis_pair(features_df, synthesis_type, key_features, readable_names):
    """
    Анализ пары Natural vs конкретный тип синтеза (FastPitch или VITS)

    Args:
        synthesis_type: 'fastpitch' или 'vits'
    """

    # Фильтрация данных: только real и выбранный тип
    df_pair = features_df[
        (features_df['synthesis_type'] == 'real') |
        (features_df['synthesis_type'] == synthesis_type)
    ].copy()

    print(f"\n Размер выборки:")
    print(f"   Real: {(df_pair['synthesis_type'] == 'real').sum()}")
    print(f"   {synthesis_type.capitalize()}: {(df_pair['synthesis_type'] == synthesis_type).sum()}")

    # Метки: 0 = real, 1 = fake
    labels = (df_pair['synthesis_type'] == synthesis_type).astype(int)

    # Анализ каждого признака
    results = {}

    print(f"\n Расчет EER для {len(key_features)} признаков...")

    for feature in tqdm(key_features, desc="EER расчет"):
        if feature not in df_pair.columns:
            continue

        scores = df_pair[feature].values

        # Статистики по классам
        real_values = df_pair[df_pair['synthesis_type'] == 'real'][feature]
        fake_values = df_pair[df_pair['synthesis_type'] == synthesis_type][feature]

        # Вычисление EER
        eer, threshold = compute_eer(scores, labels)

        diff = fake_values.mean() - real_values.mean()
        diff_pct = (abs(diff) / real_values.mean() * 100) if real_values.mean() != 0 else 0

        results[feature] = {
            'eer': eer,
            'threshold': threshold,
            'mean_real': real_values.mean(),
            'mean_fake': fake_values.mean(),
            'std_real': real_values.std(),
            'std_fake': fake_values.std(),
            'diff': diff,
            'diff_pct': diff_pct
        }

    # Сортировка по EER (лучшие первые)
    results = dict(sorted(results.items(), key=lambda x: x[1]['eer']))

    # Вывод топ-5
    print(f"\n ТОП-5 признаков для детекции {synthesis_type.upper()}:")
    for i, (feature, stats) in enumerate(list(results.items())[:5], 1):
        readable = readable_names.get(feature, feature)
        print(f"\n{i}. {readable}")
        print(f"   EER: {stats['eer']:.3f} ({stats['eer']*100:.1f}% ошибок)")
        print(f"   Real: {stats['mean_real']:.4f} ± {stats['std_real']:.4f}")
        print(f"   Fake: {stats['mean_fake']:.4f} ± {stats['std_fake']:.4f}")
        print(f"   Разница: {stats['diff']:+.4f} ({stats['diff_pct']:+.1f}%)")

    return df_pair, results


# ЗАПУСК АНАЛИЗА FASTPITCH
df_fastpitch, results_fastpitch = analyze_synthesis_pair(
    features_df,
    'fastpitch',
    key_features,
    readable_feature_names
)

"""Анализ:
1. Качество синтеза: FastPitch имитирует естественную речь очень хорошо — лучший признак дает только 38.7% точности.

2. Главная уязвимость: Механистичность пауз

- FastPitch делает паузы на 13.7% более однородными
- Это единственный признак с EER < 40%

3. Паттерн различий:

- Хорошо имитируется: спектр (+1.9%), громкость (+3.5%)
- Слабое место: временные параметры (паузы +13.7%, длительность +4.3%)

Одиночные признаки неэффективны для детекции FastPitch. Система синтезирует речь качественно, с минимальными артефактами только в ритмической структуре.


"""

df_vits, results_vits = analyze_synthesis_pair(
    features_df,
    'vits',
    key_features,
    readable_feature_names
)

"""Анализ:
1. Качество синтеза: VITS показывает результат чуть хуже FastPitch — лучший признак дает 36.1% ошибок (против 38.7% у FastPitch).

2. Главная уязвимость: Вариативность пауз (EER 36.1%)

VITS делает паузы на 25.1% более разнообразными (не однородными, как FastPitch!)
- Real: 0.0589 ± 0.0286
- VITS: 0.0737 ± 0.0439 (больше разброс)

3. Паттерн различий:

- Паузы: +25.1% (противоположно FastPitch!)
- Интонация: +20.8% (скорость повышения)
- Громкость: +4.4% (похоже на FastPitch)
- Длительность: +2.7% (хорошо)
4. Отличие от FastPitch:

FastPitch: паузы слишком однородные (-13.7%)
VITS: паузы слишком разнообразные (+25.1%)
VITS хуже с интонацией (+20.8% против FastPitch)

VITS легче детектируется, чем FastPitch. Его слабости: избыточная вариативность пауз и неестественная динамика интонации.

## FastPitch и VITS
"""

import matplotlib.pyplot as plt
import seaborn as sns

def compare_synthesis_systems(results_fp, results_vits, readable_names):
    """
    Сравнение эффективности признаков для FastPitch и VITS
    """

    comparison_data = []

    for feature in results_fp.keys():
        if feature in results_vits:
            comparison_data.append({
                'Признак': readable_names.get(feature, feature)[:45],
                'EER_FastPitch': results_fp[feature]['eer'],
                'EER_VITS': results_vits[feature]['eer'],
                'Diff_FP': results_fp[feature]['diff_pct'],
                'Diff_VITS': results_vits[feature]['diff_pct'],
                'Разница_EER': abs(results_fp[feature]['eer'] - results_vits[feature]['eer']),
                'Лучше_для': 'FastPitch' if results_fp[feature]['eer'] < results_vits[feature]['eer'] else 'VITS'
            })

    df_comp = pd.DataFrame(comparison_data)
    df_comp = df_comp.sort_values('Разница_EER', ascending=False)

    print(f"\n Таблица сравнения (отсортировано по различию EER):")
    print(df_comp[['Признак', 'EER_FastPitch', 'EER_VITS', 'Разница_EER', 'Лучше_для']].to_string(index=False))

    # Статистика
    fp_better = (df_comp['Лучше_для'] == 'FastPitch').sum()
    vits_better = (df_comp['Лучше_для'] == 'VITS').sum()

    print(f"   Признаков, где FastPitch труднее детектировать: {fp_better}")
    print(f"   Признаков, где VITS труднее детектировать: {vits_better}")
    print(f"   Средний EER FastPitch: {df_comp['EER_FastPitch'].mean():.3f}")
    print(f"   Средний EER VITS: {df_comp['EER_VITS'].mean():.3f}")

    # Визуализация
    fig, axes = plt.subplots(2, 2, figsize=(16, 12))

    # График 1: Scatter plot - сравнение EER
    ax1 = axes[0, 0]
    ax1.scatter(df_comp['EER_FastPitch'], df_comp['EER_VITS'],
                s=150, alpha=0.6, c='steelblue', edgecolors='black', linewidths=2)
    ax1.plot([0.3, 0.6], [0.3, 0.6], 'r--', linewidth=2, label='Одинаковая эффективность')
    ax1.set_xlabel('EER для FastPitch', fontsize=13, fontweight='bold')
    ax1.set_ylabel('EER для VITS', fontsize=13, fontweight='bold')
    ax1.set_title('Сравнение эффективности признаков\n(ближе к линии = похожая детектируемость)',
                  fontsize=14, fontweight='bold')
    ax1.legend(fontsize=11)
    ax1.grid(True, alpha=0.3)
    ax1.set_xlim(0.3, 0.6)
    ax1.set_ylim(0.3, 0.6)

    # Аннотации для крайних точек
    for _, row in df_comp.nlargest(3, 'Разница_EER').iterrows():
        ax1.annotate(row['Признак'][:25],
                    xy=(row['EER_FastPitch'], row['EER_VITS']),
                    xytext=(10, 10), textcoords='offset points',
                    fontsize=9, alpha=0.8,
                    bbox=dict(boxstyle='round,pad=0.4', facecolor='yellow', alpha=0.4),
                    arrowprops=dict(arrowstyle='->', color='gray'))

    # График 2: Bar plot - ТОП-5 для каждой системы
    ax2 = axes[0, 1]
    top5 = df_comp.nsmallest(5, 'EER_FastPitch')

    x = np.arange(len(top5))
    width = 0.35

    bars1 = ax2.barh(x - width/2, top5['EER_FastPitch'], width,
                     label='FastPitch', color='coral', alpha=0.8, edgecolor='black')
    bars2 = ax2.barh(x + width/2, top5['EER_VITS'], width,
                     label='VITS', color='skyblue', alpha=0.8, edgecolor='black')

    ax2.set_yticks(x)
    ax2.set_yticklabels([f[:35] for f in top5['Признак']], fontsize=10)
    ax2.set_xlabel('EER (меньше = лучше детекция)', fontsize=12, fontweight='bold')
    ax2.set_title('ТОП-5 признаков для детекции', fontsize=14, fontweight='bold')
    ax2.legend(fontsize=11)
    ax2.invert_yaxis()
    ax2.grid(True, alpha=0.3, axis='x')

    # График 3: Различия в средних значениях
    ax3 = axes[1, 0]
    features_plot = df_comp.nlargest(8, 'Разница_EER')['Признак'].tolist()
    diff_fp = [df_comp[df_comp['Признак'] == f]['Diff_FP'].values[0] for f in features_plot]
    diff_vits = [df_comp[df_comp['Признак'] == f]['Diff_VITS'].values[0] for f in features_plot]

    x = np.arange(len(features_plot))
    width = 0.35

    ax3.barh(x - width/2, diff_fp, width, label='FastPitch', color='coral', alpha=0.8)
    ax3.barh(x + width/2, diff_vits, width, label='VITS', color='skyblue', alpha=0.8)

    ax3.set_yticks(x)
    ax3.set_yticklabels([f[:30] for f in features_plot], fontsize=9)
    ax3.set_xlabel('Разница от Real (%)', fontsize=12, fontweight='bold')
    ax3.set_title('Направление и величина отличий от натуральной речи',
                  fontsize=14, fontweight='bold')
    ax3.axvline(x=0, color='black', linestyle='-', linewidth=1)
    ax3.legend(fontsize=11)
    ax3.invert_yaxis()
    ax3.grid(True, alpha=0.3, axis='x')

    # График 4: Сводная таблица
    ax4 = axes[1, 1]
    ax4.axis('tight')
    ax4.axis('off')

    summary_data = [
        ['Метрика', 'FastPitch', 'VITS', 'Победитель'],
        ['─'*20, '─'*15, '─'*15, '─'*15],
        ['Средний EER', f"{df_comp['EER_FastPitch'].mean():.3f}",
         f"{df_comp['EER_VITS'].mean():.3f}",
         'FastPitch' if df_comp['EER_FastPitch'].mean() > df_comp['EER_VITS'].mean() else 'VITS'],
        ['Лучший EER', f"{df_comp['EER_FastPitch'].min():.3f}",
         f"{df_comp['EER_VITS'].min():.3f}",
         'FastPitch' if df_comp['EER_FastPitch'].min() > df_comp['EER_VITS'].min() else 'VITS'],
        ['Худший EER', f"{df_comp['EER_FastPitch'].max():.3f}",
         f"{df_comp['EER_VITS'].max():.3f}",
         'FastPitch' if df_comp['EER_FastPitch'].max() > df_comp['EER_VITS'].max() else 'VITS'],
        ['Признаков труднее\nдетектировать', str(fp_better), str(vits_better),
         'FastPitch' if fp_better > vits_better else 'VITS'],
    ]

    table = ax4.table(cellText=summary_data, cellLoc='center', loc='center',
                     colWidths=[0.3, 0.2, 0.2, 0.3])
    table.auto_set_font_size(False)
    table.set_fontsize(11)
    table.scale(1, 2.5)

    # Стилизация таблицы
    for i in range(len(summary_data)):
        for j in range(4):
            cell = table[(i, j)]
            if i == 0:
                cell.set_facecolor('#4472C4')
                cell.set_text_props(weight='bold', color='white')
            elif i == 1:
                cell.set_facecolor('#E7E6E6')
            else:
                cell.set_facecolor('#F2F2F2' if i % 2 == 0 else 'white')

    ax4.set_title('Сводная статистика\n(больший EER = труднее детектировать)',
                  fontsize=14, fontweight='bold', pad=20)

    plt.suptitle('Сравнительный анализ FastPitch и VITS',
                 fontsize=16, fontweight='bold', y=0.995)
    plt.tight_layout()
    plt.savefig('/content/synthesis_comparison.png', dpi=300, bbox_inches='tight')
    plt.show()

    return df_comp


comparison_df = compare_synthesis_systems(
    results_fastpitch,
    results_vits,
    readable_feature_names
)

"""Анализ:
1. FastPitch немного качественнее:

Средний EER: 0.495 (FastPitch) vs 0.502 (VITS)
FastPitch труднее детектировать по 6 признакам, VITS — по 7

2. Ключевые различия систем:

FastPitch:

- Лучше имитирует: спектр, громкость, ритм
- Слабость: однородные паузы (-13.7%)

VITS:

- Лучше имитирует: высоту голоса, длительность пауз
- Слабости: избыточная вариативность пауз (+25.1%), неестественная интонация (+20.8%)
3. Наибольшие различия между системами:

Спектр: FastPitch на 13.4% труднее (EER 0.45 vs 0.59)
Громкость: FastPitch на 9.9% труднее (EER 0.51 vs 0.61)
Интонация: VITS на 9% труднее (EER 0.44 vs 0.53)


Обе системы очень качественные (средний EER ~50% ≈ случайное угадывание). FastPitch чуть лучше в целом, но имеет противоположные артефакты: FastPitch делает паузы слишком стабильными, VITS — слишком хаотичными.

## Кросс-тестирование моделей
"""

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, roc_auc_score, classification_report
import numpy as np

def cross_test_models(features_df, key_features, readable_names):
    """
    Кросс-тестирование:
    - Обучение на FastPitch → тест на VITS
    - Обучение на VITS → тест на FastPitch
    """
    print("\n" + "="*80)
    print("КРОСС-ТЕСТИРОВАНИЕ МОДЕЛЕЙ")
    print("="*80)

    # Подготовка данных
    df_real = features_df[features_df['synthesis_type'] == 'real']
    df_fastpitch = features_df[features_df['synthesis_type'] == 'fastpitch']
    df_vits = features_df[features_df['synthesis_type'] == 'vits']

    print(f"\n📊 Размеры выборок:")
    print(f"   Real: {len(df_real)}")
    print(f"   FastPitch: {len(df_fastpitch)}")
    print(f"   VITS: {len(df_vits)}")

    # Выбор признаков
    X_cols = key_features

    # ============================================================
    # Тест 1: Обучение на FastPitch → Тест на VITS
    # ============================================================
    print("\n" + "─"*80)
    print("ТЕСТ 1: Модель обучена на FastPitch → тестируется на VITS")
    print("─"*80)

    # Обучающая выборка: Real + FastPitch
    train_fp = pd.concat([df_real, df_fastpitch])
    X_train_fp = train_fp[X_cols]
    y_train_fp = (train_fp['synthesis_type'] == 'fastpitch').astype(int)

    # Тестовая выборка: Real + VITS
    test_vits = pd.concat([df_real, df_vits])
    X_test_vits = test_vits[X_cols]
    y_test_vits = (test_vits['synthesis_type'] == 'vits').astype(int)

    # Обучение модели
    model_fp = RandomForestClassifier(n_estimators=100, max_depth=10, random_state=42)
    model_fp.fit(X_train_fp, y_train_fp)

    # Предсказание на VITS
    y_pred_vits = model_fp.predict(X_test_vits)
    y_pred_proba_vits = model_fp.predict_proba(X_test_vits)[:, 1]

    acc_fp_on_vits = accuracy_score(y_test_vits, y_pred_vits)
    roc_fp_on_vits = roc_auc_score(y_test_vits, y_pred_proba_vits)

    print(f"\n📈 Результаты:")
    print(f"   Accuracy: {acc_fp_on_vits:.3f} ({acc_fp_on_vits*100:.1f}%)")
    print(f"   ROC-AUC:  {roc_fp_on_vits:.3f}")
    print(f"\n📋 Детальный отчет:")
    print(classification_report(y_test_vits, y_pred_vits,
                                target_names=['Real', 'VITS'], digits=3))

    # ============================================================
    # Тест 2: Обучение на VITS → Тест на FastPitch
    # ============================================================
    print("\n" + "─"*80)
    print("ТЕСТ 2: Модель обучена на VITS → тестируется на FastPitch")
    print("─"*80)

    # Обучающая выборка: Real + VITS
    train_vits = pd.concat([df_real, df_vits])
    X_train_vits = train_vits[X_cols]
    y_train_vits = (train_vits['synthesis_type'] == 'vits').astype(int)

    # Тестовая выборка: Real + FastPitch
    test_fp = pd.concat([df_real, df_fastpitch])
    X_test_fp = test_fp[X_cols]
    y_test_fp = (test_fp['synthesis_type'] == 'fastpitch').astype(int)

    # Обучение модели
    model_vits = RandomForestClassifier(n_estimators=100, max_depth=10, random_state=42)
    model_vits.fit(X_train_vits, y_train_vits)

    # Предсказание на FastPitch
    y_pred_fp = model_vits.predict(X_test_fp)
    y_pred_proba_fp = model_vits.predict_proba(X_test_fp)[:, 1]

    acc_vits_on_fp = accuracy_score(y_test_fp, y_pred_fp)
    roc_vits_on_fp = roc_auc_score(y_test_fp, y_pred_proba_fp)

    print(f"\n📈 Результаты:")
    print(f"   Accuracy: {acc_vits_on_fp:.3f} ({acc_vits_on_fp*100:.1f}%)")
    print(f"   ROC-AUC:  {roc_vits_on_fp:.3f}")
    print(f"\n📋 Детальный отчет:")
    print(classification_report(y_test_fp, y_pred_fp,
                                target_names=['Real', 'FastPitch'], digits=3))

    # ============================================================
    # Сравнение с "родными" моделями
    # ============================================================
    print("\n" + "="*80)
    print("СРАВНЕНИЕ С ОБУЧЕНИЕМ НА ТОЙ ЖЕ СИСТЕМЕ")
    print("="*80)

    # Модель на FastPitch (для справки)
    model_fp_native = RandomForestClassifier(n_estimators=100, max_depth=10, random_state=42)
    model_fp_native.fit(X_train_fp, y_train_fp)
    y_pred_fp_native = model_fp_native.predict(X_test_fp)
    y_pred_proba_fp_native = model_fp_native.predict_proba(X_test_fp)[:, 1]
    acc_fp_native = accuracy_score(y_test_fp, y_pred_fp_native)
    roc_fp_native = roc_auc_score(y_test_fp, y_pred_proba_fp_native)

    # Модель на VITS (для справки)
    model_vits_native = RandomForestClassifier(n_estimators=100, max_depth=10, random_state=42)
    model_vits_native.fit(X_train_vits, y_train_vits)
    y_pred_vits_native = model_vits_native.predict(X_test_vits)
    y_pred_proba_vits_native = model_vits_native.predict_proba(X_test_vits)[:, 1]
    acc_vits_native = accuracy_score(y_test_vits, y_pred_vits_native)
    roc_vits_native = roc_auc_score(y_test_vits, y_pred_proba_vits_native)

    # Итоговая таблица
    results_summary = pd.DataFrame({
        'Сценарий': [
            'FastPitch → FastPitch (родная)',
            'VITS → FastPitch (кросс)',
            'VITS → VITS (родная)',
            'FastPitch → VITS (кросс)'
        ],
        'Accuracy': [
            acc_fp_native,
            acc_vits_on_fp,
            acc_vits_native,
            acc_fp_on_vits
        ],
        'ROC-AUC': [
            roc_fp_native,
            roc_vits_on_fp,
            roc_vits_native,
            roc_fp_on_vits
        ]
    })

    print("\n📊 Итоговая таблица:")
    print(results_summary.to_string(index=False))

    # Визуализация
    fig, axes = plt.subplots(1, 2, figsize=(16, 6))

    # График 1: Accuracy
    ax1 = axes[0]
    scenarios = ['FP→FP\n(родная)', 'VITS→FP\n(кросс)', 'VITS→VITS\n(родная)', 'FP→VITS\n(кросс)']
    accuracies = results_summary['Accuracy'].values
    colors = ['green', 'orange', 'green', 'orange']

    bars = ax1.bar(scenarios, accuracies, color=colors, alpha=0.7, edgecolor='black', linewidth=2)
    ax1.set_ylabel('Accuracy', fontsize=13, fontweight='bold')
    ax1.set_title('Сравнение точности моделей', fontsize=14, fontweight='bold')
    ax1.set_ylim(0, 1)
    ax1.axhline(y=0.5, color='red', linestyle='--', label='Случайное угадывание')
    ax1.legend()
    ax1.grid(True, alpha=0.3, axis='y')

    for bar, acc in zip(bars, accuracies):
        height = bar.get_height()
        ax1.text(bar.get_x() + bar.get_width()/2., height + 0.02,
                f'{acc:.3f}\n({acc*100:.1f}%)',
                ha='center', va='bottom', fontsize=11, fontweight='bold')

    # График 2: ROC-AUC
    ax2 = axes[1]
    roc_aucs = results_summary['ROC-AUC'].values

    bars2 = ax2.bar(scenarios, roc_aucs, color=colors, alpha=0.7, edgecolor='black', linewidth=2)
    ax2.set_ylabel('ROC-AUC', fontsize=13, fontweight='bold')
    ax2.set_title('Сравнение ROC-AUC моделей', fontsize=14, fontweight='bold')
    ax2.set_ylim(0, 1)
    ax2.axhline(y=0.5, color='red', linestyle='--', label='Случайное угадывание')
    ax2.legend()
    ax2.grid(True, alpha=0.3, axis='y')

    for bar, roc in zip(bars2, roc_aucs):
        height = bar.get_height()
        ax2.text(bar.get_x() + bar.get_width()/2., height + 0.02,
                f'{roc:.3f}',
                ha='center', va='bottom', fontsize=11, fontweight='bold')

    plt.suptitle('Кросс-тестирование: обобщающая способность моделей',
                 fontsize=16, fontweight='bold')
    plt.tight_layout()
    plt.savefig('/content/cross_testing_results.png', dpi=300, bbox_inches='tight')
    plt.show()

    return results_summary


# ЗАПУСК КРОСС-ТЕСТИРОВАНИЯ
results_summary = cross_test_models(features_df, key_features, readable_feature_names)

"""Основные результаты

1. Модели демонстрируют хорошую способность к обобщению между системами

При кросс-тестировании получены следующие результаты:

- Модель, обученная на VITS и протестированная на FastPitch: точность 77.5%, ROC-AUC 0.932
- Модель, обученная на FastPitch и протестированная на VITS: точность 79.9%, ROC-AUC 0.942

Для сравнения, модели, обученные и протестированные на данных одной системы:

- FastPitch (обучение и тест на FastPitch): точность 98.7%, ROC-AUC 0.999
- VITS (обучение и тест на VITS): точность 99.4%, ROC-AUC 0.999
- Пояснение термина "родные модели": модели, которые обучались и тестировались на данных одной и той же системы синтеза речи (например, обучение на FastPitch, тестирование на FastPitch).

2. Снижение качества при кросс-тестировании составляет приблизительно 20%
- При тестировании на данных той же системы: 98-99% точность
- При тестировании на данных другой системы: 77-80% точность
- Потеря точности: 18-22 процентных пункта
3. Наблюдается асимметрия результатов

Модель FastPitch → VITS показывает более высокую точность (79.9%)
Модель VITS → FastPitch показывает более низкую точность (77.5%)
Разница составляет 2.4 процентных пункта
4. Практические выводы
Положительные аспекты:

- Модели переносятся между системами значительно лучше случайного классификатора (50% точность)
- ROC-AUC 0.93-0.94 указывает на хорошую различительную способность

Ограничения:

Существуют специфические артефакты каждой системы:
FastPitch характеризуется механистичными паузами
VITS демонстрирует избыточную вариативность пауз и неестественную интонацию
Общий вывод:
Несмотря на разнонаправленные артефакты синтеза, модели успешно выявляют общие признаки синтетической речи (параметры громкости, спектра, ритма), что обеспечивает приемлемую точность кросс-системной детекции на уровне 78%.

Вывод

Кросс-тестирование показало, что модели Random Forest, обученные на данных одной TTS-системы (Real + FastPitch или Real + VITS), достигают почти идеальной точности 98-99% при тестировании на этой же системе, но при переносе на другую систему точность падает до 77-80% (что близко к результатам исходного исследования 72.7%), подтверждая, что каждая система имеет специфические акустические артефакты (FastPitch — механистичные паузы, VITS — хаотичные паузы и неестественная интонация), однако модели успешно улавливают общие признаки синтетической речи (громкость, спектр, ритм), обеспечивая приемлемую универсальную детекцию на уровне 72-80% независимо от типа TTS-системы.
"""